apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-uno
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dionmm/demo-app-uno.git
    targetRevision: HEAD
    path: dev
    kustomize:
      # Optional image name prefix
      namePrefix: dev-
      # Optional images passed to "kustomize edit set image".
      images:
      - gcr.io/heptio-images/ks-guestbook-demo:0.2

  destination:
    server: https://kubernetes.default.svc
    namespace: app-uno
    
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true