apiVersion: v1
kind: Service
metadata:
  name: app-uno-svc
spec:
  selector:
    app: app-uno
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1234
    - protocol: TCP
      port: 443
      targetPort: 56789